theme: minima
title: My blog on GitHub Pages (title)
author: Szymon
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is description of my blog with sample text.

# social links
github_username:  B0GD4NS # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
